In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
from sklearn import preprocessing

In [2]:
kdd = pd.read_csv("kddcup99.csv")
#data read

In [3]:
kdd.shape
#no of row and column

(494020, 42)

In [4]:
kdd.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,label
0,0,tcp,http,SF,181,5450,0,0,0,0,...,9,1.0,0.0,0.11,0.0,0.0,0.0,0.0,0.0,normal
1,0,tcp,http,SF,239,486,0,0,0,0,...,19,1.0,0.0,0.05,0.0,0.0,0.0,0.0,0.0,normal
2,0,tcp,http,SF,235,1337,0,0,0,0,...,29,1.0,0.0,0.03,0.0,0.0,0.0,0.0,0.0,normal
3,0,tcp,http,SF,219,1337,0,0,0,0,...,39,1.0,0.0,0.03,0.0,0.0,0.0,0.0,0.0,normal
4,0,tcp,http,SF,217,2032,0,0,0,0,...,49,1.0,0.0,0.02,0.0,0.0,0.0,0.0,0.0,normal

In [5]:
kdd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 494020 entries, 0 to 494019
Data columns (total 42 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   duration                     494020 non-null  int64
 1   protocol_type                494020 non-null  object
 2   service                      494020 non-null  object
 3   flag                         494020 non-null  object
 4   src_bytes                    494020 non-null  int64
 5   dst_bytes                    494020 non-null  int64
 6   land                         494020 non-null  int64
 7   wrong_fragment               494020 non-null  int64
 8   urgent                       494020 non-null  int64
 9   hot                          494020 non-null  int64
 10  num_failed_logins            494020 non-null  int64
 11  logged_in                    494020 non-null  int64
 12  lnum_compromised             494020 non-null  int64
 13  lroot_shell                  494020 non-null  int64
 14  lsu_attempted                494020 non-null  int64
 15  lnum_root                    494020 non-null  int64
 16  lnum_file_creations          494020 non-null  int64
 17  lnum_shells                  494020 non-null  int64
 18  lnum_access_files            494020 non-null  int64
 19  lnum_outbound_cmds           494020 non-null  int64
 20  is_host_login                494020 non-null  int64
 21  is_guest_login               494020 non-null  int64
 22  count                        494020 non-null  int64
 23  srv_count                    494020 non-null  int64
 24  serror_rate                  494020 non-null  float64
 25  srv_serror_rate              494020 non-null  float64
 26  rerror_rate                  494020 non-null  float64
 27  srv_rerror_rate              494020 non-null  float64
 28  same_srv_rate                494020 non-null  float64
 29  diff_srv_rate                494020 non-null  float64
 30  srv_diff_host_rate           494020 non-null  float64
 31  dst_host_count               494020 non-null  int64
 32  dst_host_srv_count           494020 non-null  int64
 33  dst_host_same_srv_rate       494020 non-null  float64
 34  dst_host_diff_srv_rate       494020 non-null  float64
 35  dst_host_same_src_port_rate  494020 non-null  float64
 36  dst_host_srv_diff_host_rate  494020 non-null  float64
 37  dst_host_serror_rate         494020 non-null  float64
 38  dst_host_srv_serror_rate     494020 non-null  float64
 39  dst_host_rerror_rate         494020 non-null  float64
 40  dst_host_srv_rerror_rate     494020 non-null  float64
 41  label                        494020 non-null  object
dtypes: float64(15), int64(23), object(4)
memory usage: 158.3+ MB

In [6]:
print('kddcup99 dataset details: ')
for col_name in kdd.columns:
  if kdd[col_name].dtypes == 'object' :
    unique_cat = len(kdd[col_name].unique())
    print("Feature '{col_name}' has {unique_cat} categories".format(col_name=col_name, unique_cat=unique_cat))

kddcup99 dataset details:
Feature 'protocol_type' has 3 categories
Feature 'service' has 66 categories
Feature 'flag' has 11 categories
Feature 'label' has 23 categories

In [7]:
kdd.describe(include=object)

       protocol_type service    flag   label
count         494020  494020  494020  494020
unique             3      66      11      23
top             icmp   ecr_i      SF   smurf
freq          283602  281400  378439  280790

In [8]:
kdd.isnull().sum()
#null value

duration                       0
protocol_type                  0
service                        0
flag                           0
src_bytes                      0
dst_bytes                      0
land                           0
wrong_fragment                 0
urgent                         0
hot                            0
num_failed_logins              0
logged_in                      0
lnum_compromised               0
lroot_shell                    0
lsu_attempted                  0
lnum_root                      0
lnum_file_creations            0
lnum_shells                    0
lnum_access_files              0
lnum_outbound_cmds             0
is_host_login                  0
is_guest_login                 0
count                          0
srv_count                      0
serror_rate                    0
srv_serror_rate                0
rerror_rate                    0
srv_rerror_rate                0
same_srv_rate                  0
diff_srv_rate                  0
srv_diff_host_rate             0
dst_host_count                 0
dst_host_srv_count             0
dst_host_same_srv_rate         0
dst_host_diff_srv_rate         0
dst_host_same_src_port_rate    0
dst_host_srv_diff_host_rate    0
dst_host_serror_rate           0
dst_host_srv_serror_rate       0
dst_host_rerror_rate           0
dst_host_srv_rerror_rate       0
label                          0
dtype: int64

In [9]:
label_mapping={
    'back':'Dos',
    'land':'Dos',
    'neptune':'Dos',
    'pod':'Dos',
    'smurf':'Dos',
    'teardrop':'Dos',
    'ipsweep':'Probe',
    'nmap':'Probe',
    'portsweep':'Probe',
    'satan':'Probe',
    'ftp_write':'R2L',
    'guess_passwd':'R2L',
    'imap':'R2L',
    'multihop':'R2L',
    'phf':'R2L',
    'spy':'R2L',
    'warezclient':'R2L',
    'warezmaster':'R2L',
    'loadmodule':'U2R',
    'buffer_overflow':'U2R',
    'rootkit':'U2R',
    'perl':'U2R',
    'normal':'Normal'
}
kdd['label']=kdd['label'].map(label_mapping)

In [10]:
kdd['label'].unique()
#get unique values

array(['Normal', 'U2R', 'Dos', 'R2L', 'Probe'], dtype=object)

In [11]:
label_encoder=preprocessing.LabelEncoder()
kdd['label']=label_encoder.fit_transform(kdd['label'])
print(kdd['label'])
#Train.head()
#using label encoder

0         1
1         1
2         1
3         1
4         1
         ..
494015    1
494016    1
494017    1
494018    1
494019    1
Name: label, Length: 494020, dtype: int32

In [12]:
categorical_columns = ['protocol_type', 'service', 'flag']

kdd_encoded = kdd[categorical_columns]

In [13]:
kdd_encoded

       protocol_type service flag
0                tcp    http   SF
1                tcp    http   SF
2                tcp    http   SF
3                tcp    http   SF
4                tcp    http   SF
...              ...     ...  ...
494015           tcp    http   SF
494016           tcp    http   SF
494017           tcp    http   SF
494018           tcp    http   SF
494019           tcp    http   SF

[494020 rows x 3 columns]

In [14]:
from sklearn.preprocessing import LabelEncoder

kdd_categorical_values_enc=kdd_encoded.apply(LabelEncoder().fit_transform)
#label encoder

In [15]:
enc = OneHotEncoder(categories='auto')
kdd_categorical_values_encenc = enc.fit_transform(kdd_categorical_values_enc)
kdd_cat_data=pd.DataFrame(kdd_categorical_values_encenc.toarray())
kdd_cat_data.head()

,0,1,2,3,4,5,6,7,8,9,...,70,71,72,73,74,75,76,77,78,79
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [16]:
#Join encoded categorical data and drop non categorical data
kdd1=kdd.join(kdd_cat_data)
kdd1.drop('flag', axis=1, inplace=True)
kdd1.drop('protocol_type', axis=1, inplace=True)
kdd1.drop('service', axis=1, inplace=True)

print(kdd1.shape)

(494020, 119)

In [17]:
#Trains=Train1.drop("label",axis=1)

#Tests=Test1.drop("label",axis=1)

#print(Trains.shape, Tests.shape)

In [18]:
import numpy as np

# Find the minimum and maximum values in the column
min_val = np.min(kdd1)
max_val = np.max(kdd1)

# Perform MinMax normalization
kddcup = (kdd1 - min_val) / (max_val - min_val)

In [19]:
def convertfloattoint(value):
    if value ==0.0:
        return 0
    else:
        return 1

In [20]:
kddcup=kddcup.applymap(convertfloattoint)

In [21]:
kddcup.head()

,duration,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,logged_in,lnum_compromised,...,70,71,72,73,74,75,76,77,78,79
0,0,1,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
1,0,1,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
2,0,1,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,0,1,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
4,0,1,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0

In [22]:
import pandas as pd
from sklearn.model_selection import train_test_split

x= kddcup.iloc[:, :-1] 
x.shape

(494020, 118)

In [23]:
y = kddcup['label']
y.shape
print(y)

0         1
1         1
2         1
3         1
4         1
         ..
494015    1
494016    1
494017    1
494018    1
494019    1
Name: label, Length: 494020, dtype: int64

In [24]:
#pip install tensorflow
#install tensorflow

In [25]:
# Split the dataset into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

# Display the shapes of the resulting sets
print("Train set shape:", x_train.shape, y_train.shape)
print("Test set shape:", x_test.shape, y_test.shape)

Train set shape: (395216, 118) (395216,)
Test set shape: (98804, 118) (98804,)

# Stacked Contractive Autoencoder

In [26]:
input_dim = x_train.shape[1]
input_dim

118

In [27]:
import numpy as np
from keras.layers import Input, Dense, Reshape, Flatten, Conv2D, MaxPooling2D, UpSampling2D
from keras.models import Model
from keras.optimizers import Adam
from keras.regularizers import l2
import matplotlib.pyplot as plt 
from keras.layers import Input, Dense
from keras import regularizers
from keras.losses import mse
import keras.backend as K

# Create the autoencoder
def create_autoencoder(input_shape, latent_dim, stack_depth):
    # Create input layer
    input_layer = Input(shape=input_shape)
    
    # Create encoding layers
    encoded = input_layer
    for i in range(stack_depth):
        encoded = Dense(input_shape[0] * 2, activation='relu', kernel_regularizer=l2(1e-4))(encoded)
    
    # Create decoding layers
    decoded = encoded
    for i in range(stack_depth):
        decoded = Dense(input_shape[0] * 2, activation='relu', kernel_regularizer=l2(1e-4))(decoded)
    
    # Create output layer
    output_layer = Dense(np.prod(input_shape), activation='sigmoid')(decoded)
    output_layer = Reshape(input_shape)(output_layer)
    
    # Compile the model
    autoencoder = Model(input_layer, output_layer)
    autoencoder.compile(optimizer=Adam(learning_rate=0.0001), loss='mse')
    
    return autoencoder

# Load your data here
data = x_train

# Define the shape of your input data    
input_shape = (118,)

# Define the latent dimension and stack depth
latent_dim = 64
stack_depth = 3

# Create the autoencoder
autoencoder = create_autoencoder(input_shape, latent_dim, stack_depth)

# Train the autoencoder
autoencoder.fit(x_train,x_train, epochs=10, batch_size=32, shuffle=True)

WARNING:tensorflow:From D:\jupyter\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

WARNING:tensorflow:From D:\jupyter\Lib\site-packages\keras\src\backend.py:1398: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

Epoch 1/10
WARNING:tensorflow:From D:\jupyter\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

12351/12351 [==============================] - 75s 6ms/step - loss: 0.0156
Epoch 2/10
12351/12351 [==============================] - 64s 5ms/step - loss: 0.0054
Epoch 3/10
12351/12351 [==============================] - 68s 6ms/step - loss: 0.0045
Epoch 4/10
12351/12351 [==============================] - 56s 5ms/step - loss: 0.0042
Epoch 5/10
12351/12351 [==============================] - 52s 4ms/step - loss: 0.0040
Epoch 6/10
12351/12351 [==============================] - 51s 4ms/step - loss: 0.0039
Epoch 7/10
12351/12351 [==============================] - 52s 4ms/step - loss: 0.0038
Epoch 8/10
12351/12351 [==============================] - 51s 4ms/step - loss: 0.0037
Epoch 9/10
12351/12351 [==============================] - 51s 4ms/step - loss: 0.0037
Epoch 10/10
12351/12351 [==============================] - 52s 4ms/step - loss: 0.0036

In [28]:
x_train.shape

autoencoder.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 input_1 (InputLayer)        [(None, 118)]             0

 dense (Dense)               (None, 236)               28084

 dense_1 (Dense)             (None, 236)               55932

 dense_2 (Dense)             (None, 236)               55932

 dense_3 (Dense)             (None, 236)               55932

 dense_4 (Dense)             (None, 236)               55932

 dense_5 (Dense)             (None, 236)               55932

 dense_6 (Dense)             (None, 118)               27966

 reshape (Reshape)           (None, 118)               0

=================================================================
Total params: 335710 (1.28 MB)
Trainable params: 335710 (1.28 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [29]:
import tensorflow as tf
encoder = tf.keras.Model(inputs=autoencoder.input,outputs=autoencoder.get_layer('dense_3').output)
x_features = encoder.predict(x_train)
x_features

12351/12351 [==============================] - 21s 2ms/step

array([[0.        , 0.        , 0.23082042, ..., 0.        , 0.        ,
        0.5282268 ],
       [0.        , 0.        , 0.33801535, ..., 0.        , 0.        ,
        0.6754032 ],
       [0.        , 0.        , 0.08104633, ..., 0.        , 0.        ,
        0.1329607 ],
       ...,
       [0.        , 0.        , 0.33801535, ..., 0.        , 0.        ,
        0.6754032 ],
       [0.        , 0.        , 0.29453027, ..., 0.        , 0.        ,
        0.61246485],
       [0.        , 0.        , 0.08104633, ..., 0.        , 0.        ,
        0.1329607 ]], dtype=float32)

In [30]:
x_test_features = encoder.predict(x_test)
x_features.shape

3088/3088 [==============================] - 6s 2ms/step

(395216, 236)

# SVM

In [31]:
import pandas as pd
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report

In [32]:
# Create SVM model
svm_model = SVC(kernel='linear',C=1)

# Train the model
svm_model.fit(x_features, y_train)

SVC(C=1, kernel='linear')

In [33]:
# Make predictions
y_pred = svm_model.predict(x_test_features)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("Classification Report:\n", report)

Accuracy: 0.974282417715882
Classification Report:
               precision    recall  f1-score   support

           0       0.98      0.99      0.98     78354
           1       0.97      0.90      0.94     20450

    accuracy                           0.97     98804
   macro avg       0.97      0.95      0.96     98804
weighted avg       0.97      0.97      0.97     98804